### ISSUE TITLE
Roadmap to 3.0

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#1447]
I've been making many changes to the `master` branch and thought about writing down where I'm going.

# To-dos
## Rules
- [x] Rename the "Attribute" rule to "Property"
- [ ] Create `Attribute` rule
- [ ] Create `Chain` rule
- [ ] Extract rules `MoreThan` and `MoreThanOrEqual` from the `Min` rule
- [ ] Extract rules `LessThan` and `LessThanOrEqual` from the `Max` rule
- [ ] Split the `Between` rule into `BetweenInclusive` and `BetweenExclusive`
- [ ] Split the `Key` rule into `KeyPresent`, `KeyMandatory`, and `KeyOptional.`
- [ ] Split the `Property` rule into `PropertyPresent`, `PropertyMandatory`, and `PropertyOptional`
- [ ] Change the behaviour of Length, Max, and Min

## Core
- [x] Use PHP Attributes to define templates
- [ ] Update validation engine (todo: split into different tasks)

## Other
- [ ] Rename branch `master` to `main`
- [ ] More integration tests for `oneOf`, `allOf` and `each` validator messages.
- [ ] Increase code coverage from 96% to 98%
- [ ] Get my credentials for @TheRespectPanda accounts in order
- [ ] Extra documentation for most common support issues
  - [ ] Message translation approaches
  - [ ] Navigating the messages tree manually
  - [ ] Using validators with custom names 
  - [ ] Expressing boolean algebra

----

# Rules

## `Attribute` rule

This rule should validate properties that have PHP attributes on them.

```php
final class Person
{
    #[Email]
    private string $email;

    public function __contruct($email)
    {
        $this->email = $email;
    }
}


v::attribute()->assert(new Person('henriquemoodygmail.com'));
// -> "email" must be valid email
```

Attribute could use the `Property` rule under the hood, although it might be more complicated than implementing it separately.

## Create a `chain` rule

In a few cases, you would only want to move to the subsequent validation if the previous one was successful. This is particularly useful for internals. You can understand it if you look into the Domain rule.

It would be similar to `AllOf` instead of evaluating all rules.

```php
v::chain(v::stringType(), v::noWhitespace(), v::contains('.'))->assert('This is useful');
// It would never evaluate with v::contains('.'), because it fails already on v::noWhitespace()
```

## Change the behaviour of Length, Max, and Min

The idea would be to allow those rules to accept rules that are "comparable." Something like:

* `Length(ComparableRule $rule)`
* `Max(ComparableRule $rule)`
* `Min(ComparableRule $rule)`

Here are some examples:

```php
v::length(v::equals(3))->validate($input);
v::length(v::betweenInclusive(1, 5))->validate($input);
v::max(v::greaterThan(3))->validate($input);
v::min(v::lessThan('now'))->validate($input);
```

# Core

## Update validation engine

Here are some "problems" I see with the current engine

* Allowing each rule to execute `assert()` and `check()` means duplication in some cases.
* Because we use exceptions to assert/check, we can only invert a validation (with `Not`) if there are errors. That means that we have limited granularity control.
* There is a lot of logic in the exceptions. That means that even after an exception is thrown, something could still happen. We're stable on that front, but I want to simplify them. Besides, debugging exception code is painful because the stack track stops once the exception constructor is created.

On version 3.0, this won't be possible anymore:

```php
$email = new Email():
$email->assert($input);
```

Instead, you would need to do that:

```php
$validator = new Validator(new Email());
$validator->assert($input);
```

However, because `assert()` and `check()` will be available only on `Validator`, you could do things like that:

```php
// Passing the template as a string
v::email()->assert($input, 'Uff... {{input}} should have been an email');

// Passing an custom exception
v::email()->assert($input, new DomainException('Customers must have valid emails'));

// Passing an erray of templates
v::intValue()->positive()->lessThan(5)->assert($input, [
    'intValue' => 'Area must be an integer',
    'positive' => 'Area must be a positive number',
    'lessThan' => 'Area cannot be bigger than m2',
]);
```

**Comment by dmitriiPopov** [comment]
Hello, guys. When will you continue working on release 3.0?

**Comment by dmjohnsson23** [comment]
Are there any of these unfinished items you've listed that would be good for a new contributor to handle? We're using this library, and this 3.0 release looks like it will fix some of the issues we've had with it, so I could probably put some time toward a few issues to help get the release out.

**Comment by henriquemoody** [comment]
I'm sorry for be belated response, peeps!

@dmitriiPopov, I've been working a lot in the last couple of weeks. I'm hoping to release version 3.0 at the beginning of next year. I think it's looking great so far, check this out: https://github.com/Respect/Validation/blob/main/docs/02-feature-guide.md

@dmjohnsson23, at the moment it's a bit tricky, because I'm at a phase that I'm myself figuring out how I really want things to work. I got most of the groundwork done, but I'm still seeing how I really want a few rules to work out. Thank you for offering help, though!

🐼

**Comment by henriquemoody** [comment]
@dmjohnsson23, if you (or anyone) could do what I did for Length in https://github.com/Respect/Validation/pull/1485 but for Each, Min, and/or Max, that would be very helpful. I've been coding intensely in the past month, I'm gonna take a break until next year, but I will probably be able to review merge requests.

**Comment by dmjohnsson23** [comment]
I'd be happy to give it a go. I looked at the referenced commit and I don't fully understand what all the changes are doing at this point, so I'll need to spend some time figuring out the code. I don't just want to copy/paste the same changes without fully understanding the intent. Any pointers would be welcome.

**Comment by andus4n** [comment]
**Replace setTemplate() with Templated rule**
I'm doing a lot of stuff like this:
```
->allOf(v::attribute(v::stringType()->length(1, 19)->digit()->intVal())->setTemplate('This should have been valid...'))
->allOf(v::attribute(v::boolType())->setTemplate('This also should have been valid...'))
```

Will this still be valid in 3.0?

**Comment by henriquemoody** [comment]
@andus4n, a few things will need to be replaced in your code:

1. `AllOf` will require at least 2 rules ([ref](https://github.com/Respect/Validation/blob/main/docs/rules/AllOf.md))
2. `Attribute` will be called `Property` -- assuming you forgot to type the property name there ([ref](https://github.com/Respect/Validation/blob/main/docs/rules/Property.md))
3. `Length` will change a bit ([ref](https://github.com/Respect/Validation/blob/main/docs/rules/Length.md))

However, even on the current versions, I think your chain could be simpler. I'm not sure why you're calling `setTemplate()` on the chain of the `attribute` rule instead of calling it in the chain of rule you're passing to `attribute`, could you elaborate?

I think that on version 2.3 (or 2.4), you chain could look like this:

```php
->attribute('foo', v::stringType()->length(1, 19)->digit()->intVal()->setTemplate('This should have been valid...'))
->attribute('bar', v::boolType()->setTemplate('This also should have been valid...'))
```

In version 3.0, it will look like pretty much the same (just changing `attribute` -> `property` and `length` -> `lengthBetween`)

```php
->property('foo', v::stringType()->lengthBetween(1, 19)->digit()->intVal()->setTemplate('This should have been valid...'))
->property('bar', v::boolType()->setTemplate('This also should have been valid...'))
```

But, it could be more clear (IMO) on version 3.0:

```php
->property('foo', v::templated(v::stringType()->lengthBetween(1, 19)->digit()->intVal(), 'This should have been valid...'))
->property('bar', v::templated(v::boolType(), 'This also should have been valid...'))
```

**Comment by andus4n** [comment]
Thank you for the response.
I'm still using v2.2.4.

> AllOf will require at least 2 rules

So basically, if i have a chain like `v::stringType()->lengthBetween(1, 19)` **inside** `allOf` it'll still be seen as a single rule?
In other words, `v::allOf(v::stringType()->lengthBetween(1, 19))` will raise an error?
I'm usin' a lot of chaining and if i'd wrap them inside `allOf`, this would allow me to use the `setTemplate()` method if anything fails.

To be more precise:
`v::allOf(v::stringType()->lengthBetween(1, 19))->setTemplate('Invalid.')` - this'll actually give me an exception with my custom message.
`v::stringType()->lengthBetween(1, 19)->setTemplate('Invalid')` - this'll generate an internal exception message, ignoring my custom template.
Is this fixed in version 2.3 / 2.4?

> Attribute will be called Property -- assuming you forgot to type the property name there
> Length will change a bit and you'll be able to use it as a prefix

This won't be a problem.
At this point i think that my best bet is to rewrite my rules in order to be able to properly use v3.0.

**Comment by henriquemoody** [comment]
> _So basically, if i have a chain like `v::stringType()->lengthBetween(1, 19)` **inside** allOf it'll still be seen as a single rule?
In other words, `v::allOf(v::stringType()->lengthBetween(1, 19))` will raise an error?_

By error, I mean that it won't work, because `allOf` will required at least two rules, while `v::stringType()->lengthBetween(1, 19)` is, for `allOf` a single `Validator` rule.


> _I'm usin' a lot of chaining and if i'd wrap them inside allOf, this would allow me to use the setTemplate() method if anything fails._

Oh, I got it. So you're using `allOf` as a way to contain chains, so you can template them as a single unit. It's not way it was intended to, but that's a smart way of using it! That would be exactly the purpose of `Templated` rule in version 3.0

> _As a side-note, will version 2.2.4 work on PHP 8.4? I think a lot of developers are still using this version._

I think so! Apart form the `sf` rule, all tests are passing.

**Comment by faabiosr** [comment]
Hi! I opened a PR to rename the `Result->isValid`, I would like to know the reason of renaming, even though, I opened. Please let me know if this change is needed.

https://github.com/Respect/Validation/pull/1535

**Comment by henriquemoody** [comment]
I wrote a blog post so everyone can get a glimpse of what's coming on v3: https://dev.to/henriquemoody/what-is-new-on-respectvalidation-30-37no

**Comment by henriquemoody** [comment]
Version 3.0.0 is finally out! https://github.com/Respect/Validation/releases/tag/3.0.0
